### ISSUE TITLE
Stack smashing when login

### ISSUE THREAD

**Issue by adamcavendish** [GangZhuo/BaiduPCS#177]
I got stack smashing when login. What can I do?

`*** stack smashing detected ***: pcs terminated`

---

I'm using latest pcs built today.

**Comment by adamcavendish** [comment]
stack trace:

```
#0  0x00007ffff6e6a428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6e6c02a in __GI_abort () at abort.c:89
#2  0x00007ffff6eac7ea in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff6fc38a2 "*** %s ***: %s terminated\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6f4d56c in __GI___fortify_fail (msg=<optimized out>, msg@entry=0x7ffff6fc3884 "stack smashing detected") at fortify_fail.c:37
#4  0x00007ffff6f4d510 in __stack_chk_fail () at stack_chk_fail.c:28
#5  0x0000000000417afe in passport_dv_imitate_input_username ()
#6  0x0000000000417ea1 in passport_dv_imitate ()
#7  0x0000000000418236 in passport_build_dv ()
#8  0x00000000004094b2 in pcs_dologin ()
#9  0x000000000040a794 in pcs_login ()
#10 0x000000000042acca in cmd_login ()
#11 0x000000000042da7f in exec_cmd ()
#12 0x000000000042e014 in main ()
```

**Comment by GangZhuo** [comment]
Try latest code.

**Comment by adamcavendish** [comment]
You're awesome!!! Thx.
