### ISSUE TITLE
无法登陆账号，无限验证邮箱验证码

### ISSUE THREAD

**Issue by fantastlcok** [GangZhuo/BaiduPCS#181]
测试了三台服务器，一直在循环要求输入验证码，邮箱验证码。
我保证以上验证码绝对没有输入错误。

**Comment by GangZhuo** [comment]
我这边不能重新，暂时未找到原因

**Comment by fantastlcok** [comment]
@GangZhuo 能不能手动填写COOKIE文件？我看挺多人反馈无限循环验证这个问题。

**Comment by bbscool** [comment]
浏览器登陆，抓取cookie，用下面这个网址转换成netscape风的cookie。然后替换C:\Users\（用户）\.pcs\default.cookie里的内容就行了。
http://crdx.org/misc/cookies/

当年出中文验证码cli无法登陆的时候我就是这么弄得。效果不错。@fantastlcok

**Comment by kittgo** [comment]
Mark 楼上

**Comment by mayuuko** [comment]
請問如何用http://crdx.org/misc/cookies/這網址转换成netscape风的cookie?
我已經找到浏览器的cookie檔, 那Domain和Input填什麼?

**Comment by zelda0079** [comment]
https://github.com/GangZhuo/BaiduPCS_NET/issues/10
NET版也有同样情况

**Comment by giveup** [comment]
@mayuuko Chrome用户使用[cookies.txt](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg) 即可导出整个cookies，netscape格式。替换同名文件。

**Comment by yongmz** [comment]
@giveup 用你的方法解决了，感谢！

**Comment by zelda0079** [comment]
net版不知可否用同样方法解决？

**Comment by zelda0079** [comment]
NET版好像用不到

**Comment by vizv** [comment]
@GangZhuo 我这里也是用 Cookie 解决了，用验证码一直崩溃……

```
#0  0x00007ffff6cf3dfc in __strncmp_sse42 () from /lib64/libc.so.6
#1  0x000000000041ac34 in skip_comments (in=0x0) at pcs/cJSON.c:265
#2  0x000000000041ad3e in skip (in=0x0) at pcs/cJSON.c:295
#3  0x000000000041b7ae in parse_object (item=0x669d80,
    value=0x779d70 ":{\"mobile\":'' || '',        \"verifymobile\":'',\"email\":'[CENSORED]',\"softtoken\":'',\"password\":'',\"original_mobile\":'',\"original_email\":''", ' ' <repeats 16 times>, "},\"countrycode\":\"\",    \"traceid\": \"\"}") at pcs/cJSON.c:472
#4  0x000000000041aff9 in parse_value (item=0x669d80,
    value=0x779cc0 "{\"errno\":'110000',\"msg\":'',\"forgot\":'http:\\/\\/passport.baidu.com\\/?getpassappeal&tpl=&code=a773eb294df0caa3c01b8391&bdToken=9bd13bcd409f48a9d211ffc41db3b7b1&from=verify',\"data\":{\"mobile\":'' || '',    "...) at pcs/cJSON.c:335
#5  0x000000000041adb4 in cJSON_ParseWithOpts (
    value=0x779cc0 "{\"errno\":'110000',\"msg\":'',\"forgot\":'http:\\/\\/passport.baidu.com\\/?getpassappeal&tpl=&code=a773eb294df0caa3c01b8391&bdTok
en=9bd13bcd409f48a9d211ffc41db3b7b1&from=verify',\"data\":{\"mobile\":'' || '',    "..., return_parse_end=0x0, require_null_terminated=0)
    at pcs/cJSON.c:309
#6  0x000000000041ae4b in cJSON_Parse (
    value=0x779cc0 "{\"errno\":'110000',\"msg\":'',\"forgot\":'http:\\/\\/passport.baidu.com\\/?getpassappeal&tpl=&code=a773eb294df0caa3c01b8391&bdToken=9bd13bcd409f48a9d211ffc41db3b7b1&from=verify',\"data\":{\"mobile\":'' || '',    "...) at pcs/cJSON.c:318
#7  0x0000000000428ac3 in pcs_call_authwidgetverify (handle=0x647420,
    authtoken=0x752bb0 "775dkHduX2SblX2WTlXLTyvNmDgFL9h81hjEWqs9HqlMWopRxoocKBqNsgK3hEeIMPUsBJ5TAa5LwvSN%2F6LlxAR%2BvetaUxYmckWc7QD4S%2B%2BCxYHQ01SJcssJUSnfRb%2FQgfnPo1ISCLUh2Ttg2j48dRRNVnG0g6WZ%2F0dILMUv07JZRX%2BW7ytSa4J3ch"..., vtype=0x438950 "", action=0x438c20 "getapi", vcode=0x438950 "",
    errorno=0x7fffffffe2f0, authsid=0x0, pdata=0x7fffffffde38,
    pmsg=0x7fffffffe2e8) at pcs/pcs.c:1753
#8  0x00000000004291ad in pcs_do_auth_verify (handle=0x647420,
    authtoken=0x752bb0 "775dkHduX2SblX2WTlXLTyvNmDgFL9h81hjEWqs9HqlMWopRxoocKBqNsgK3hEeIMPUsBJ5TAa5LwvSN%2F6LlxAR%2BvetaUxYmckWc7QD4S%2B%2BCxYHQ01SJcssJUSnfRb%2FQgfnPo1ISCLUh2Ttg2j48dRRNVnG0g6WZ%2F0dILMUv07JZRX%2BW7ytSa4J3ch"..., res_error=0x7fffffffe344, authsid=0x7fffffffe338) at pcs/pcs.c:1915
#9  0x0000000000429996 in pcs_login (handle=0x647420) at pcs/pcs.c:2086
#10 0x000000000041153d in cmd_login (context=0x7fffffffe470,
    arg=0x7fffffffe4e0) at shell.c:5985
#11 0x00000000004140a7 in exec_cmd (context=0x7fffffffe470,
    arg=0x7fffffffe4e0) at shell.c:6912
#12 0x00000000004145ea in main (argc=2, argv=0x7fffffffe608)
    at shell.c:7007
```

**Comment by mj0786** [comment]
http://crdx.org/misc/cookies not work
