### ISSUE TITLE
现在登录输入完验证码就pcs已停止工作

### ISSUE THREAD

**Issue by wsz2074480** [GangZhuo/BaiduPCS#263]
昨天申诉了一次，电脑pcs要重新登录，现在发现登录的时候输入验证码（四位英文或者两位中文）就已停止。

**Comment by RichardRo** [comment]
同样的问题，输完验证码报segment fault.

**Comment by zichenshan** [comment]
同样的问题。

**Comment by RichardRo** [comment]
找到原因了，参考下面这个问题：
[https://github.com/GangZhuo/BaiduPCS/issues/181](url)
链接里有人贴出一段出错时的打印：
`#6  0x000000000041ae4b in cJSON_Parse (
    value=0x779cc0 "{\"errno\":'110000',\"msg\":'',\"forgot\":'http:\\/\\/passport.baidu.com\\/?getpassappeal&tpl=&code=a773eb294df0caa3c01b8391&bdToken=9bd13bcd409f48a9d211ffc41db3b7b1&from=verify',\"data\":{\"mobile\":'' || '',    "...) at pcs/cJSON.c:318
#7  0x0000000000428ac3 in pcs_call_authwidgetverify (handle=0x647420,
    authtoken=0x752bb0 "775dkHduX2SblX2WTlXLTyvNmDgFL9h81hjEWqs9HqlMWopRxoocKBqNsgK3hEeIMPUsBJ5TAa5LwvSN%2F6LlxAR%2BvetaUxYmckWc7QD4S%2B%2BCxYHQ01SJcssJUSnfRb%2FQgfnPo1ISCLUh2Ttg2j48dRRNVnG0g6WZ%2F0dILMUv07JZRX%2BW7ytSa4J3ch"..., vtype=0x438950 "", action=0x438c20 "getapi", vcode=0x438950 "",
    errorno=0x7fffffffe2f0, authsid=0x0, pdata=0x7fffffffde38,
    pmsg=0x7fffffffe2e8) at pcs/pcs.c:1753`
里面的这段：
`http:\\/\\/passport.baidu.com\\/?getpassappeal&tpl=&code=a773eb294df0caa3c01b8391&bdToken=9bd13bcd409f48a9d211ffc41db3b7b1&from=verify`
在浏览器里打开，发现是账号已经被百度锁定了，需要申诉。程序里没有考虑到这种情况，后面处理出问题了。
目前的解决办法是按上面的链接，修改default.cookie。具体方法：
下载chrome浏览器，安装cookies.txt插件，然后登录百度盘，点cookies.txt插件，拷贝弹出窗口里的内容，替换default.cookie。
替换之后就可以不用登录直接使用命令了，用完以后不要logout。
cookie好像有时限，过段时间登录会失效，目前我是设置了crontab，定时执行baidupcs list /命令来保活，用了几天，目前还没有出问题。

**Comment by hollylee** [comment]
\"mobile\":'' || ''

This is a malformed JSON
